import { OperationalEntity } from "./operational-map.types";

export const REAL_OPERATIONAL_ENTITIES: OperationalEntity[] = [
  {
    id: "occ-001",
    type: "occurrence",
    title: "Apreensão de Entorpecentes",
    description: "Ação preventiva realizada durante patrulhamento ostensivo.",
    address: "Av. Rodrigo Otávio, Japiim",
    neighborhood: "Japiim",
    zone: "Sul",
    coordinates: [-59.988, -3.118],
    updatedAt: "Há 12 minutos",
  },
  {
    id: "occ-002",
    type: "occurrence",
    title: "Ocorrência em Verificação",
    description: "Registro sob análise de inteligência regional.",
    address: "Rua Teresina, Adrianópolis",
    neighborhood: "Adrianópolis",
    zone: "Centro-Sul",
    coordinates: [-60.012, -3.111],
    updatedAt: "Há 45 minutos",
  },
  {
    id: "per-001",
    type: "person",
    title: "Registro de Interesse - Indivíduo A",
    description: "Pessoa monitorada com vínculo organizacional confirmado.",
    address: "Rua Pará, Nossa Senhora das Graças",
    neighborhood: "Nossa Senhora das Graças",
    zone: "Centro-Sul",
    coordinates: [-60.019, -3.116],
    updatedAt: "Há 2 horas",
  },
  {
    id: "veh-001",
    type: "vehicle",
    title: "Veículo Suspeito Monitorado",
    description: "Placa identificada em ponto de interesse operacional.",
    address: "Av. Cosme Ferreira, Coroado",
    neighborhood: "Coroado",
    zone: "Leste",
    coordinates: [-59.965, -3.098],
    updatedAt: "Há 3 horas",
  },
  {
    id: "alt-001",
    type: "alert",
    title: "Alerta Prioritário de Área",
    description: "Aumento de movimentação atípica no perímetro.",
    address: "Av. Torquato Tapajós, Flores",
    neighborhood: "Flores",
    zone: "Centro-Sul",
    coordinates: [-60.028, -3.068],
    updatedAt: "Há 10 minutos",
  },
];